### ISSUE TITLE
Add {dittodb} to the scaffolding of the ropensci docs

### ISSUE THREAD

**Issue by jonkeane** [ropensci/dittodb#130]
The [rOpenSci docs recommend some testing packages](https://devguide.ropensci.org/building.html#recommended-scaffolding), submit a PR to those docs recommending using {dittodb}

**Comment by maelle** [comment]
It's mentioned in an item of https://devguide.ropensci.org/building.html#testing

> If your package interacts with a database you might find [dittodb](https://docs.ropensci.org/dittodb) useful.

**Comment by jonkeane** [comment]
Closing this as done – thanks for the link @maelle !
