### ISSUE TITLE
Move testthat from Imports to Suggests

### ISSUE THREAD

**Issue by cocinerox** [ropensci/dittodb#154]
Hello! Thank you for this great package. I noticed that since https://github.com/ropensci/dittodb/commit/539bec19 it no longer uses `testthat::with_mock` in `with_mock_db`, hence it doesn't need to import `testthat`. For projects that use e.g. `tinytest` instead of `testthat` it would be very advantageous not to import it. (Also, the second clause in the last paragraph of "Developing {dittodb}" vignette is not valid any more.)

**Comment by jonkeane** [comment]
I would be happy to make this change. Would you be interested in sending a PR with the needed changes?
