### ISSUE TITLE
Release dbtest 0.1.0

### ISSUE THREAD

**Issue by jonkeane** [ropensci/dittodb#49]
Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] Polish pkgdown reference index 
* [x] Draft blog post 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [x] Update install instructions in README 
* [x] Finish blog post 
* [x] Tweet 
* [x] Add link to blog post in pkgdown news menu

**Comment by pachamaltese** [comment]
maybe I'd send this to rOpenSci peer review before CRAN
I can add another vignette based on what I do at work

**Comment by jonkeane** [comment]
I've opened a pre-submission issue at https://github.com/ropensci/software-review/issues/366

**Comment by jonkeane** [comment]
Before we submit, make sure the links are ok:

https://stat.ethz.ch/pipermail/r-package-devel/2020q2/005564.html

**Comment by jonkeane** [comment]
🎉 done! 

https://cran.r-project.org/web/packages/dittodb/index.html
